server:
  port: 10001
  tomcat:
    max-threads: 200
    max-connections: 200
    min-spare-threads: 50
    accept-count: 1000
    uri-encoding: UTF-8

spring:
  application:
    name: expo-sso-service
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml