spring:
  datasource:
    url: jdbc:mysql://139.199.26.103:3306/expo?useUnicode=true&characterEncoding=utf8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    tomcat:
      max-active: 20
      max-wait: 1000
      min-idle: 1
      initial-size: 3
  cloud:
    zookeeper:
      connect-string: 139.199.26.103:2181

